services:
  nestjs:
    container_name: nestjs
    image: nestjs:1.0.2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - name=value
    restart: unless-stopped
    ports:
      - 3000:3000
    command: "node ./dist/main.js"
    depends_on:
      nestjs:
        condition: service_healthy
    healthcheck:
      test: "curl http://localhost:3000/"
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 30s