services:
  nestjs:
    container_name: nestjs
    image: nestjs:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - name=value
    restart: unless-stopped
    ports:
      - 3000:3000
    command: "node ./dist/main.js"